spring:
  application:
    name: render-form-service

server:
  port: 8899

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# to avoid java.util.concurrent.TimeoutException on first hystrix execution
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000